apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: zipkin
  name: zipkin
spec:
  ports:
  - name: "9411"
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    service: zipkin
status:
  loadBalancer: {}
